# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raemp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='f_name_kanji',
            field=models.CharField(max_length=20, verbose_name='名前（漢字）'),
        ),
    ]
