# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raemp', '0002_auto_20170912_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='f_name_kanji',
            field=models.CharField(max_length=20),
        ),
    ]
