# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 03:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raemp', '0004_auto_20171031_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='', verbose_name='画像ファイル')),
                ('created_at', models.DateField(default=datetime.datetime.now, verbose_name='作成日')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='更新日')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now, verbose_name='作成日'),
        ),
        migrations.AddField(
            model_name='location',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='更新日'),
        ),
        migrations.AddField(
            model_name='person',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now, verbose_name='作成日'),
        ),
        migrations.AddField(
            model_name='person',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='更新日'),
        ),
        migrations.AddField(
            model_name='shop',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now, verbose_name='作成日'),
        ),
        migrations.AddField(
            model_name='shop',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='更新日'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_address',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='raemp.Location', verbose_name='住所'),
        ),
    ]
