# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 03:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raemp', '0007_auto_20171106_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('notes', models.TextField(max_length=100)),
                ('created_at', models.DateField(default=datetime.datetime.now, verbose_name='作成日')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='更新日')),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raemp.Shop', verbose_name='対象店舗')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raemp.TempStaff', verbose_name='対象要員')),
            ],
        ),
    ]
