# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raemp', '0008_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempstaff',
            name='home_address',
        ),
        migrations.AddField(
            model_name='tempstaff',
            name='rank_type',
            field=models.CharField(choices=[('S', 'Sランク'), ('A', 'Aランク'), ('B', 'Bランク'), ('C', 'Cランク'), ('D', 'Dランク'), ('E', 'Eランク')], default=None, max_length=1, verbose_name='ランク'),
        ),
    ]
